<?php namespace Peteleco\PayU\Tests;

use Peteleco\PayU\Support\Environment;
use PHPUnit\Framework\TestCase as MainTestCase;

/**
 * Class TestCase
 *
 * @see     http://developers.payulatam.com/pt/api/considerations.html
 * @package PayU\Tests
 */
class TestCase extends MainTestCase
{

    /**
     * @var Environment
     *
     */
    public $environment;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->environment = new Environment(
            'pRRXKOl8ikMmt9u',
            '4Vj8eK4rloUd272L48hsrarnUA',
            '508029',
            '512327',
            true
        );
    }
}